# Generated by Django 6.0.6 on 2026-07-02 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('qr_code', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_repair', 'In repair'), ('maintenance_due', 'Maintenance due'), ('missing', 'Missing'), ('retired', 'Retired')], db_index=True, default='active', max_length=20)),
                ('condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment/photos/')),
                ('notes', models.TextField(blank=True)),
                ('last_action_type', models.CharField(blank=True, choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('status_change', 'Status change'), ('assign', 'Assign'), ('return', 'Return'), ('maintenance_complete', 'Maintenance complete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export')], max_length=30)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='categories.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='sites.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='equipment_e_status_fb8540_idx'), models.Index(fields=['site'], name='equipment_e_site_id_febaef_idx'), models.Index(fields=['category'], name='equipment_e_categor_3d1cd8_idx'), models.Index(fields=['assigned_to'], name='equipment_e_assigne_96ad0d_idx'), models.Index(fields=['created_at'], name='equipment_e_created_ddb06c_idx'), models.Index(fields=['site', 'status'], name='equipment_e_site_id_3970c3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('purchase_cost__isnull', True), ('purchase_cost__gte', 0), _connector='OR'), name='equipment_purchase_cost_non_negative')],
            },
        ),
    ]
