# Generated by Django 6.0.6 on 2026-07-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('status_change', 'Status change'), ('assign', 'Assign'), ('return', 'Return'), ('maintenance_complete', 'Maintenance complete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('register', 'Self-registered'), ('password_reset', 'Password reset')], db_index=True, max_length=30),
        ),
    ]
